### ISSUE TITLE
[IOOBE] Ctrl-X during column selection mode

### ISSUE THREAD

**Issue by dancioca** [denis-zhdanov/intellij-plugin-copy-on-steroids#8]
Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=88,keyText=X,keyChar=Cancel,modifiers=Ctrl,extModifiers=Ctrl,keyLocation=KEY_LOCATION_STANDARD,rawCode=88,primaryLevelUnicode=120,scancode=45,extendedKeyCode=0x58] on frame0: Wrong offset: -1; count:118691
java.lang.IndexOutOfBoundsException: Wrong offset: -1; count:118691
    at com.intellij.openapi.editor.impl.CharArray.charAt(CharArray.java:419)
    at org.denis.AbstractCopyPasteSyntaxAwareProcessor$Context.addTextIfPossible(AbstractCopyPasteSyntaxAwareProcessor.java:627)
    at org.denis.AbstractCopyPasteSyntaxAwareProcessor$Context.onIterationEnd(AbstractCopyPasteSyntaxAwareProcessor.java:653)
    at org.denis.AbstractCopyPasteSyntaxAwareProcessor.collectTransferableData(AbstractCopyPasteSyntaxAwareProcessor.java:121)
    at com.intellij.codeInsight.editorActions.CopyHandler.execute(CopyHandler.java:83)
    at com.intellij.codeInsight.editorActions.CutHandler.executeWriteAction(CutHandler.java:73)
    at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:54)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1013)
    at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.execute(EditorWriteActionHandler.java:37)
    at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:82)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:93)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:67)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:480)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:334)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by denis-zhdanov** [comment]
Please turn on debug mode at plugin settings, reproduce the problem and upload your idea.log

**Comment by dancioca** [comment]
The issue is consistently reproducible (tried with java / xml file content):
1. turn "Column Selection Mode" on
2. select something
3. Press Ctrl-X (cut)

Additionally, Ctrl-C (copy) does not do anything if column selection mode is ON (clipboard content remains unchanged from the last successful copy).

(Can not upload debug log cause it may leak proprietary code which could bring me in trouble)
